### ISSUE TITLE
Concurrency issue

### ISSUE THREAD

**Issue by matrixbegins** [delight-im/ShortURL#16]
HI Ujjawal,

Thanks for these excellent examples. Its not an issue but a question about implementation.

How this implementation ensures the concurrency issue?. Is it an auto-incremented id from the database and then we should pass that to this code?

**Comment by ocram** [comment]
This library is completely separate from your implementation of assigning, storing and loading unique IDs.

You can use your database's *auto-incrementing* integer IDs. If that doesn't work for you (e.g. due to replication, cluster setup, etc.) as you suggest, you can use any other *integer* IDs, e.g. `UUID_SHORT()` in MySQL, as suggested [here](https://github.com/delight-im/ShortURL/issues/15).

As long as you have integers, this library can encode (shorten) and decode ("un-shorten") them.
