### ISSUE TITLE
Fixed lenght for output?

### ISSUE THREAD

**Issue by juanse417** [delight-im/ShortURL#28]
Hi!
I'm using the SQL Server class.
Is there any way to make the output encoded string to always be, let says, 12 characters?

Thanks

**Comment by ocram** [comment]
Sure!

In order to guarantee an upper limit on the output, just put an upper limit on the input. With the integer types `tinyint`, `smallint` or `int`, you should not exceed 12 characters of output at all. If you need larger inputs, e.g. from `bigint`, your maximum input number for `n` characters of output is `51^n − 1`. There's no other way to make the upper limit work.

Since what you want is 12 characters of output for *every* input, you need a lower limit as well.

The only way to make that work is by padding (e.g. on the left). Pad the output with a fixed character that is not in the alphabet of this library, up to your desired character length. If you need more variation and "randomness" in your output, consider using a set of multiple padding characters, neither of which may be in this library's alphabet. Choose the next padding character from set set randomly.

Hope that helps!
