### ISSUE TITLE
Supporting long/big-int numbers!

### ISSUE THREAD

**Issue by QVMaster** [delight-im/ShortURL#31]
`All numbers from 1 to 2,147,483,647 inclusively can be safely encoded and decoded again in all implementations.`

I think this not supporting number bigger than  2,147,483,647 is a weakness, That must be Useful to support long/big-int numbers.

**Comment by ocram** [comment]
Thanks!

The paragraph that you quoted is the only guarantee that we can give for *all* implementations. So that’s why it’s there. And it should definitely remain there.

Apart from that, you’re right in that it might be useful to extend the supported range of numbers from 32 bit to 64 bit, at least for some use cases. This must be done individually for each implementation.

**Comment by QVMaster** [comment]
I see That is true about all implementations, But as real projects in the real world will develop in one or two platforms, so when deciding to use encoding functions, absolutely we will choose without limit ones. I agree with you about individual implementation, Thanks for your heeds.
