### ISSUE TITLE
Note Limit up to 1999999999

### ISSUE THREAD

**Issue by volomike** [delight-im/ShortURL#5]
If you make a number larger than 1999999999, it won't convert backwards.

**Comment by ocram** [comment]
Thanks for your report!

What language or implementation are you referring to?
- In **Java**, you are obviously limited by what the compiler allows for `int`, i.e. `2,147,483,647`.
- In **JavaScript**, everything should work without any problems up to `Number.MAX_SAFE_INTEGER`, i.e. `9,007,199,254,740,991`.
- In **PHP**, everything should work safely up to `PHP_INT_MAX`, i.e. `2,147,483,647` or `9,223,372,036,854,775,807`, depending on your system.

So there shouldn't be any problems with `1,999,999,999` or `2,000,000,000`.

Does this help? Otherwise, can you give a specific example? Thanks!

**Comment by volomike** [comment]
You were right. Closing this ticket out. I did a variation on your routine but didn't count the length of my string properly and so my BASE constant was off by one, which created the problem.
