### ISSUE TITLE
on 64bit php, PHP_INT_MAX is decoded as a float

### ISSUE THREAD

**Issue by divinity76** [delight-im/ShortURL#7]

**Comment by ocram** [comment]
Thanks a lot for reporting this!

It isn't only decoded as `float`, it's also just _wrong_. But this is not a bug in this library. It's not even a bug in PHP. It is due to the limited precision of the [`float` or `double` number type](http://php.net/manual/de/language.types.float.php) (which are the same in PHP). This is why our PHP implementation shares this "problem" with (most) implementations we have for other languages.

The line that uncovers this problem is the (rounded down) division in the `encode` function:

``` php
$num = (int) ($num / self::BASE);
```

Passing `PHP_INT_MAX` to `encode`, that should be the following calculation right in the first iteration (which has the greatest numerator):

``` php
$num = (int) (9223372036854775807 / 51);
```

That returns `180850432095191680`, but should actually be `180850432095191682`. Note the last digit.

Thus, I'd say there are three ways to cope with this problem:
- Find out the largest input that can be safely encoded and decoded again. I'd love to learn about that number!
- Use [BC Math](http://php.net/manual/en/ref.bc.php) and (at least for large numbers) replace that line in PHP with
  
  ``` php
  $num = bcdiv($num, self::BASE);
  ```
- Use [GMP](http://php.net/manual/de/ref.gmp.php) and (at least for large numbers) replace that line in PHP with
  
  ``` php
  $num = gmp_intval(gmp_div_q($num, self::BASE));
  ```

In your application, you can ensure that either BC Math or GMP is available and then just replace that single line in `encode`.

In this library, however, I'd say we cannot do this for three reasons:
- Neither of those two libraries is _guaranteed_ to be available for everyone.
- Most of the time, this change isn't required, anyway.
- Right now, the PHP implementation is at least consistent with the other implementations.

Anyway, you can use quite large numbers, by all means everything up to `2,147,483,647`, which is `PHP_INT_MAX` in 32-bit PHP. Possibly, you can even use much larger numbers, but the limit where this stops working (at least for the pre-defined alphabet size) would have to be determined.

**Comment by divinity76** [comment]
well, until it's fixed, it should at least be clearly documented

**Comment by ocram** [comment]
You're absolutely right, of course! I didn't mean to say the current situation is perfect. The documentation is lacking, at least. Without any new information, I would put `2,147,483,647` as the upper limit into the documentation. Would you agree?

**Comment by divinity76** [comment]
"safe" upper limit, yeah sure (while the actual upper limit is unknown)

**Comment by divinity76** [comment]
btw, i tested everything from 0 to 2,147,483,647

```
for($i = 0; $i < 2147483647; ++ $i) {
    if ($i !== ShortURL::decode ( ShortURL::encode ( $i ) )) {
        var_dump ( $i );
        echo 'FAILED';
        die ();
    }
}
die ( 'NOT FOUND' );
```

pretty sure it used less than 2 hours in Win7 x64 -> VMWare -> Debian 8 x64, PHP 7.0.8 on Intel Core i7 6700HQ , anyway,  resulted in
`NOT FOUND`

**Comment by ocram** [comment]
Yes, a few months ago, I did a test for the 32-bit range as well. Everything works fine there, luckily.

But testing the full 64-bit range will take much, much longer. I don't think we'll ever manage to do that.

Anyway, we both found that we can use BC Math which provides correct results up to the maximum integer on 64-bit platforms. That's great, and probably all we'll ever need :) So we can just accept that we won't know the actual limit without BC Math.

I've added a note regarding the number range to the README now: https://github.com/delight-im/ShortURL/commit/e9b72d82eab404bcb4ec721a6f95454fbc75f728

Thanks again for this issue -- very helpful!

We'll use it as a reference for everybody who needs support for larger numbers, since we now have an easy solution available.
